### PR TITLE
 Improving the remolding aspect of Body Cultivation

### PR DESCRIPTION
**Pull request by NecrCode**
the purpose of this mod is to reduce the amount of clicks you have to do when choosing labels for your body cultivator.
this mod is still in it's infancy, and for now there's only filtering by color (rarity).

### CODE REVIEW

**Comment by iguanacore** [comment]
A slight change, not directly related to the functionality.
You've modified the TimeScale variable.
It's not a Property in the current terminology, if you actually changed the get/set functionalities, it should be listed under Functions. But since you just changed its value (and the game is paused during its usage), it shouldn't need to be separately listed.

However, have you verified that the TimeScale changes you've implemented have no unintended results on alternative game speeds? If there are no issues, then as soon as the slight change in readme is done, this can be merged.

**Comment by NecrCode** [comment]
> A slight change, not directly related to the functionality.

perhaps it could be added to features (in the future?), but for now it simply tweaks a function that returns a list of labels. so it should be in functions. but it's all up to you. :)

> It's not a Property in the current terminology

interesting, but according to docs, they are defined as properties (but they called them accessors).


> have you verified that the TimeScale changes you've implemented have no unintended results on alternative game speeds?
 
Yes, i've verified it. if the game is paused, time/day flow will remain unchanged, regardless of the changes in timeScale.

**Comment by iguanacore** [comment]
A slight change was referring to the readme and property part, not the functionality. This is a good candidate for functions, no questioning that.
The issue is that ACS and XiaWorld have an existing structure using the Property name. With fixes, there's a much clearer list of Properties modified. Calling it a property is technically correct, but irrelevant in this particular use case.

The list of new/changed entities exists mainly to provide a clear list for any compatibility related debugging. The functions can be renamed into assembly content if that makes more sense.
But more importantly, the value is only changed within the confines of the functions you've listed, not "globally". So the changes should be treated similarly to internal variables, which means that there's no need for it in the list of changes.

**Comment by NecrCode** [comment]
Removed it from REAMDE, is there anything else i missed perhaps?

**Comment by iguanacore** [comment]
Finally got around to testing it. One slight change is still required, for some odd reason, the info.json lists the version at 0.3, and not the current 0.4, but that's an easy fix. Going ahead with the change, and then merging it, just not a full release yet.

**Pull request merged**
