### PR TITLE
Skill level in Work window (mouse hover)

### PR DESCRIPTION
**Pull request by NecrCode**
when hovering above a skill, it still shows ability rather than level. so this PR will allow players to see levels on mouse hover.

### CODE REVIEW

**Review by iguanacore — CHANGES_REQUESTED** [review]
Before I start the verification process in-game and rebuilding the DLL, a few points.

The submod itself (SkillLevelEverywhere) is an optional aspect, in the sense it can be turned off under MLL settings. The current addition doesn't take that into consideration.
Some people might want to make it optional. As something that can be made optional, a similar toggle to SLE should be included.
Apart from those two configuration related aspects, there's also the part about little documentation (readme part).

- [x] "Base Mod" enable check
- [ ] Submod enable toggle
- [x] Documentation

Check the existing integrated mods (and their relevant PRs) for inspiration.

**Comment by NecrCode** [comment]
> Documentation

Already added in the PR #41 (sorry, my mistake didn't mention it here)
image


> The submod itself (SkillLevelEverywhere) is an optional aspect, in the sense it can be turned off under MLL settings. The current addition doesn't take that into considerion.

i'm kinda lost here, since the addition simply extends the functionality of SkillLevelEverywhere (`Wnd_NpcWork`), and since it's inside the said submod, if the submod is disabled then so does this function.

**Comment by iguanacore** [comment]
Yes, the documentation aspect is improved with that other PR, and is enough to start with.

> since it's inside the said submod, if the submod is disabled then so does this function.

It's a part of the same class/file, sure. But that's not the way the enabling was implemented. The functional side of things is implemented with MLL, and relies on this file:
https://github.com/iguanacore/iguana_acs_functions/blob/main/source/iguana_acs_functions/iguana_acs_functions.cs

For this submod in particular, the main lifting is done with `SkillLevelEverywhere.enabled` bool, first seen in line 11 of the changed file. And for how it's used, see lines 19 and 43. With that basic check, if the submod is disabled under MLL settings, the `return` ensures that the Patch does functionally nothing.

Your added Patch is on the same level as the other two existing patches, `Panel_NpcInfoPanel.UpdateSkill` and `Panel_NpcPropertyPanel.UpdateSkill`, and patches a function _previously untouched_. Without that bool checking, the added Patch will be utilized even when the previous two patches do functionally nothing. So for starting out, adding a similar check to your own patch (before trying, after line 66 for example) should make the proposed addition properly utilize the existing work done for enabling/disabling an aspect.

Does that make it any clearer, or should I go into more details?

**Comment by NecrCode** [comment]
No need, but Thank you for the detailed reply :) , i didn't notice the first conditional check. my mistake.

**Review by iguanacore — APPROVED** [review]

**Comment by iguanacore** [comment]
With the latest commit, it's been reworked and rebuilt. Exception catching has been disabled due to build errors. Check out KLog (found within Assembly-CSharp-firstpass.dll), would be the proper tool to use in this case.

While I see no functional difference on my end, does the new functionality work for "solving" the original issue on your instance?

**Comment by iguanacore** [comment]
Now it builds without issues, nothing seems to be broken in-game either. Merging this.

**Pull request merged**
